//generated by lazy
//author: seanlan

package v1

import (
	"TelegramBot/internal/service"
	"encoding/json"
	"github.com/gin-gonic/gin"
	"go.uber.org/zap"
	tele "gopkg.in/telebot.v3"
)

func TelegramBotWebHook(c *gin.Context) {
	zap.S().Debugf("c.Request.Body: %+v", c.Request.Body)
	var update tele.Update
	if _err := json.NewDecoder(c.Request.Body).Decode(&update); _err != nil {
		zap.S().Debugf("decode update error %v", _err)
		return
	}
	zap.S().Debugf("update %+v", update)
	name := c.Param("name")
	if name == "" {
		return
	}
	c.Set("name", name)
	_ = service.TelegramBotWebHook(c, &update)
	return
}
