//generated by lazy
//author: seanlan

package model

import "TelegramBot/internal/dao/sqlmodel"

type GetActionListReq struct {
	BaseReq
	Page int `json:"page" form:"page"`
	Size int `json:"size" form:"size"`
}

type GetActionListResp struct {
	Total   int64             `json:"total"`
	Actions []sqlmodel.Action `json:"actions"`
}

type SaveActionReq struct {
	BaseReq
}

type SaveActionResp struct {
}
