//generated by lazy
//author: seanlan

package model

type GetActionListReq struct {
	BaseReq
	Page int `json:"page" form:"page"`
	Size int `json:"size" form:"size"`
}

type GetActionListResp struct {
	Total int64 `json:"total"`
}

type SaveActionReq struct {
	BaseReq
}

type SaveActionResp struct {
}
