//generated by lazy
//author: seanlan

package model

import "TelegramBot/internal/dao/sqlmodel"

type GetConfigListReq struct {
	BaseReq
	Page int `json:"page" form:"page"`
	Size int `json:"size" form:"size"`
}

type GetConfigListResp struct {
	Total int64             `json:"total"`
	List  []sqlmodel.Config `json:"list"`
}

type SaveConfigReq struct {
	BaseReq
	ID      int    `json:"id" form:"id"`
	Key     string `json:"key" form:"key" binding:"required"`
	Value   string `json:"value" form:"value"`
	Comment string `json:"comment" form:"comment"`
}

type SaveConfigResp struct {
}
