//generated by lazy
//author: seanlan

package model

import "TelegramBot/internal/dao/sqlmodel"

type GetGroupListReq struct {
	BaseReq
	BotID int64 `json:"bot_id" form:"bot_id"`
	Page  int   `json:"page" form:"page"`
	Size  int   `json:"size" form:"size"`
}

type GetGroupListResp struct {
	Total int64                `json:"total"`
	List  []sqlmodel.BotGroups `json:"list"`
}

type SaveGroupReq struct {
	BaseReq
	ID          int64  `json:"id" form:"id"`
	BotID       int64  `json:"bot_id" form:"bot_id" binding:"required"`
	GroupTgID   int64  `json:"group_tg_id" form:"group_tg_id" binding:"required"`
	GroupTgName string `json:"group_tg_name" form:"group_tg_name" binding:"required"`
}

type SaveGroupResp struct {
}

type DeleteGroupReq struct {
	BaseReq
	ID int64 `json:"id" form:"id" binding:"required"`
}

type DeleteGroupResp struct {
}
