//generated by lazy
//author: seanlan

package model

type MessageExtType string

const (
	MessageTypeUrl    MessageExtType = "url"
	MessageTypeWebapp MessageExtType = "webapp"
)

type MessageExt struct {
	Text string         `json:"text"`
	Url  string         `json:"url"`
	Type MessageExtType `json:"type"`
}
