//generated by lazy
//author: seanlan

package model

type AdminLoginReq struct {
	BaseReq
}

type AdminLoginResp struct {
}

type ChangePasswordReq struct {
	BaseReq
}

type ChangePasswordResp struct {
}
