//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/model"
	"context"
)

func GetActionList(ctx context.Context, req model.GetActionListReq) (resp model.GetActionListResp, err error) {
	return
}

func SaveAction(ctx context.Context, req model.SaveActionReq) (resp model.SaveActionResp, err error) {
	return
}
