//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/dao"
	"TelegramBot/internal/dao/sqlmodel"
	"TelegramBot/internal/handler"
	"TelegramBot/internal/model"
	"context"
)

func GetActionList(ctx context.Context, req model.GetActionListReq) (resp model.GetActionListResp, err error) {
	resp.Total, err = dao.CountAction(ctx, nil)
	if err != nil {
		return
	}
	err = dao.FetchAllAction(ctx, &resp.Actions, nil, req.Page, req.Size)
	return
}

func SaveAction(ctx context.Context, req model.SaveActionReq) (resp model.SaveActionResp, err error) {
	var actionQ = sqlmodel.ActionColumns
	action := sqlmodel.Action{
		ID:        req.ID,
		BotName:   req.BotName,
		Command:   req.Command,
		Image:     req.Image,
		Content:   req.Content,
		Extension: req.Extension,
	}
	_, err = dao.UpsertAction(ctx, &action, dao.M{
		actionQ.BotName.FieldName:   req.BotName,
		actionQ.Command.FieldName:   req.Command,
		actionQ.Image.FieldName:     req.Image,
		actionQ.Content.FieldName:   req.Content,
		actionQ.Extension.FieldName: req.Extension,
	}, actionQ.ID.FieldName)
	if err == nil {
		handler.ClearBotActionsCache(ctx, req.BotName)
	}
	return
}
