//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/model"
	"context"
)

func GetBotList(ctx context.Context, req model.GetBotListReq) (resp model.GetBotListResp, err error) {
	return
}
func SaveBot(ctx context.Context, req model.SaveBotReq) (resp model.SaveBotResp, err error) {
	return
}
