//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/dao"
	"TelegramBot/internal/dao/sqlmodel"
	"TelegramBot/internal/model"
	"context"
)

func GetBotList(ctx context.Context, req model.GetBotListReq) (resp model.GetBotListResp, err error) {
	resp.Total, err = dao.CountBots(ctx, nil)
	if err != nil {
		return
	}
	err = dao.FetchAllBots(ctx, &resp.Bots, nil, req.Page, req.Size)
	return
}

func SaveBot(ctx context.Context, req model.SaveBotReq) (resp model.SaveBotResp, err error) {
	var botQ = sqlmodel.BotsColumns
	bot := sqlmodel.Bots{
		ID:     req.ID,
		Name:   req.Name,
		Token:  req.Token,
		Enable: req.Enable,
	}
	_, err = dao.UpsertBots(ctx, &bot, dao.M{
		botQ.Name.FieldName:   req.Name,
		botQ.Token.FieldName:  req.Token,
		botQ.Enable.FieldName: req.Enable,
	}, botQ.ID.FieldName)
	return
}
