//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/dao"
	"TelegramBot/internal/dao/sqlmodel"
	"TelegramBot/internal/model"
	"context"
)

func GetConfigList(ctx context.Context, req model.GetConfigListReq) (resp model.GetConfigListResp, err error) {
	resp.Total, err = dao.CountConfig(ctx, nil)
	if err != nil {
		return
	}
	err = dao.FetchAllConfig(ctx, &resp.List, nil, req.Page, req.Size)
	return
}

func SaveConfig(ctx context.Context, req model.SaveConfigReq) (resp model.SaveConfigResp, err error) {
	conf := sqlmodel.Config{
		ID:      req.UserID,
		Key:     req.Key,
		Value:   req.Value,
		Comment: req.Comment,
	}
	err = dao.SaveConfig(ctx, &conf)
	return
}
