//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/dao"
	"TelegramBot/internal/dao/sqlmodel"
	"TelegramBot/internal/handler"
	"TelegramBot/internal/model"
	"context"
)

func GetConfigList(ctx context.Context, req model.GetConfigListReq) (resp model.GetConfigListResp, err error) {
	resp.Total, err = dao.CountConfig(ctx, nil)
	if err != nil {
		return
	}
	err = dao.FetchAllConfig(ctx, &resp.List, nil, req.Page, req.Size)
	return
}

func SaveConfig(ctx context.Context, req model.SaveConfigReq) (resp model.SaveConfigResp, err error) {
	var configQ = sqlmodel.ConfigColumns
	conf := sqlmodel.Config{
		ID:      req.ID,
		Key:     req.Key,
		Value:   req.Value,
		Comment: req.Comment,
	}
	_, err = dao.UpsertConfig(ctx, &conf, dao.M{
		configQ.Key.FieldName:     req.Key,
		configQ.Value.FieldName:   req.Value,
		configQ.Comment.FieldName: req.Comment,
	}, configQ.ID.FieldName)
	return
}

func RefreshConfig(ctx context.Context, req model.RefreshConfigReq) (resp model.RefreshConfigResp, err error) {
	handler.ClearConfigCache(ctx)
	return
}
