//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/model"
	"context"
)

func CheckHealth(ctx context.Context, req model.CheckHealthReq) (resp model.CheckHealthResp, err error) {
	return
}
