//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/dao"
	"TelegramBot/internal/dao/sqlmodel"
	"TelegramBot/internal/handler"
	"context"
	tele "gopkg.in/telebot.v3"
)

func TelegramBotWebHook(ctx context.Context, update *tele.Update) (err error) {
	var (
		name = ctx.Value("name").(string)
		botQ = sqlmodel.BotsColumns
		bot  sqlmodel.Bots
	)
	err = dao.FetchBots(ctx, &bot, botQ.Name.Eq(name))
	if err != nil {
		return
	}
	b, err := tele.NewBot(tele.Settings{
		Token:   bot.Token,
		Offline: true,
	})
	handler.BotProcessUpdate(ctx, name, b, update)
	return
}
