//generated by lazy
//author: seanlan

package service

import (
	"TelegramBot/internal/model"
	"context"
)

func AdminLogin(ctx context.Context, req model.AdminLoginReq) (resp model.AdminLoginResp, err error) {
	return
}
func ChangePassword(ctx context.Context, req model.ChangePasswordReq) (resp model.ChangePasswordResp, err error) {
	return
}
