//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAction = "action"

var ActionColumns = struct {
	ID        FieldBase
	BotName   FieldBase
	Command   FieldBase
	Image     FieldBase
	Content   FieldBase
	Extension FieldBase
}{
	ID:        FieldBase{"id", "id"},
	BotName:   FieldBase{"bot_name", "bot_name"},
	Command:   FieldBase{"command", "command"},
	Image:     FieldBase{"image", "image"},
	Content:   FieldBase{"content", "content"},
	Extension: FieldBase{"extension", "extension"},
}

type Action struct {
	ID        int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"` //
	BotName   string `json:"bot_name" gorm:"column:bot_name;type:varchar;not null"`    //机器人名称
	Command   string `json:"command" gorm:"column:command;type:varchar;not null"`      //命令
	Image     string `json:"image" gorm:"column:image;type:varchar;not null"`          //图片
	Content   string `json:"content" gorm:"column:content;type:text;not null"`         //文本
	Extension string `json:"extension" gorm:"column:extension;type:text;not null"`     //扩展选项
}

// TableName Action's table name
func (*Action) TableName() string {
	return TableNameAction
}
