//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameAdminUser = "admin_user"

var AdminUserColumns = struct {
	ID         FieldBase
	Username   FieldBase
	Password   FieldBase
	CreateTime FieldBase
}{
	ID:         FieldBase{"id", "id"},
	Username:   FieldBase{"username", "username"},
	Password:   FieldBase{"password", "password"},
	CreateTime: FieldBase{"create_time", "create_time"},
}

type AdminUser struct {
	ID         int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`   //
	Username   string `json:"username" gorm:"column:username;type:varchar;not null"`      //用户名
	Password   string `json:"password" gorm:"column:password;type:varchar;not null"`      //密码
	CreateTime int64  `json:"create_time" gorm:"column:create_time;type:bigint;not null"` //创建时间
}

// TableName AdminUser's table name
func (*AdminUser) TableName() string {
	return TableNameAdminUser
}
