//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameBotGroups = "bot_groups"

var BotGroupsColumns = struct {
	ID          FieldBase
	BotID       FieldBase
	GroupTgID   FieldBase
	GroupTgName FieldBase
}{
	ID:          FieldBase{"id", "id"},
	BotID:       FieldBase{"bot_id", "bot_id"},
	GroupTgID:   FieldBase{"group_tg_id", "group_tg_id"},
	GroupTgName: FieldBase{"group_tg_name", "group_tg_name"},
}

type BotGroups struct {
	ID          int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`        //
	BotID       int64  `json:"bot_id" gorm:"column:bot_id;type:bigint;not null"`                //机器人ID
	GroupTgID   int64  `json:"group_tg_id" gorm:"column:group_tg_id;type:bigint;not null"`      //tg群组ID
	GroupTgName string `json:"group_tg_name" gorm:"column:group_tg_name;type:varchar;not null"` //tg群组名称
}

// TableName BotGroups's table name
func (*BotGroups) TableName() string {
	return TableNameBotGroups
}
