//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameBotMessagePush = "bot_message_push"

var BotMessagePushColumns = struct {
	ID        FieldBase
	BotID     FieldBase
	Image     FieldBase
	Content   FieldBase
	Extension FieldBase
	StartAt   FieldBase
	State     FieldBase
}{
	ID:        FieldBase{"id", "id"},
	BotID:     FieldBase{"bot_id", "bot_id"},
	Image:     FieldBase{"image", "image"},
	Content:   FieldBase{"content", "content"},
	Extension: FieldBase{"extension", "extension"},
	StartAt:   FieldBase{"start_at", "start_at"},
	State:     FieldBase{"state", "state"},
}

type BotMessagePush struct {
	ID        int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"`           //
	BotID     int64  `json:"bot_id" gorm:"column:bot_id;type:bigint;not null"`                   //
	Image     string `json:"image" gorm:"column:image;type:varchar;not null"`                    //图片
	Content   string `json:"content" gorm:"column:content;type:varchar;not null"`                //内容
	Extension string `json:"extension" gorm:"column:extension;type:varchar;not null;default:[]"` //附加选项
	StartAt   int64  `json:"start_at" gorm:"column:start_at;type:bigint;not null"`               //开始时间
	State     int32  `json:"state" gorm:"column:state;type:tinyint;not null"`                    //状态
}

// TableName BotMessagePush's table name
func (*BotMessagePush) TableName() string {
	return TableNameBotMessagePush
}
