//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameBots = "bots"

var BotsColumns = struct {
	ID     FieldBase
	Name   FieldBase
	Token  FieldBase
	Enable FieldBase
}{
	ID:     FieldBase{"id", "id"},
	Name:   FieldBase{"name", "name"},
	Token:  FieldBase{"token", "token"},
	Enable: FieldBase{"enable", "enable"},
}

type Bots struct {
	ID     int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"` //
	Name   string `json:"name" gorm:"column:name;type:varchar;not null"`            //机器人Name
	Token  string `json:"token" gorm:"column:token;type:varchar;not null"`          //token
	Enable int32  `json:"enable" gorm:"column:enable;type:tinyint;not null"`        //是否开启
}

// TableName Bots's table name
func (*Bots) TableName() string {
	return TableNameBots
}
