//generated by lazy
//author: seanlan
/**
//表结构
type BaseStruct struct {
	Package    string    //包名
	StructName string    //结构名
	TableName  string    //表名
	Members    []*Member //成员
}

// 字段结构
type Member struct {
	Name          string    //字段名
	Type          string    //字段类型
	NewType       string    //新字段类型
	ColumnName    string    //字段列名
	ColumnComment string    //字段注释
	ModelType     string    //字段模型类型
	JSONTag       string    //json tag
	GORMTag       string    //gorm tag
	NewTag        string    //新tag
}
*/

package sqlmodel

const TableNameConfig = "config"

var ConfigColumns = struct {
	ID      FieldBase
	Key     FieldBase
	Value   FieldBase
	Comment FieldBase
}{
	ID:      FieldBase{"id", "id"},
	Key:     FieldBase{"key", "key"},
	Value:   FieldBase{"value", "value"},
	Comment: FieldBase{"comment", "comment"},
}

type Config struct {
	ID      int64  `json:"id" gorm:"column:id;type:bigint;primaryKey;autoIncrement"` //
	Key     string `json:"key" gorm:"column:key;type:varchar;not null"`              //key
	Value   string `json:"value" gorm:"column:value;type:text;not null"`             //值
	Comment string `json:"comment" gorm:"column:comment;type:varchar;not null"`      //备注
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
